### PR TITLE
Add a dedicated 'Ruff: Format document' action

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We have this for lint fixing and import sorting. It seems consistent to have one for formatting too.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Hmm, not sure how I feel about that. I see the consistency but I'm not aware that any other formatter exposes such a command. What's the use case for it?

**Comment by charliermarsh** [comment]
I guess the dedicated "Ruff: Fix all" is nice if you want to run _just_ the Ruff fixes (as opposed to the generic "Fix all"). Perhaps there isn't really a use-case here for the formatter, apart from testing? Being able to run it without configuring it as your default formatter?

**Comment by MichaReiser** [comment]
Yeah, the fix all makes sense (does ruff has it's own `ruff.fixAll` quick fix?

**Comment by charliermarsh** [comment]
Yeah, it defines a custom action in the VS Code client that triggers the server command defined in the LSP.

**Pull request merged**
