### PR TITLE
Require `ruff>=0.1.0`

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR updates the minimum required version for Ruff to be `v0.1.0`. This is
because that version includes the `cell` field which will be used for Jupyter
Notebook support.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Current dependencies on/for this PR:
* main
  * **PR #283** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff-lsp/283" target="_blank">Graphite</a>  👈
    * **PR #284** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff-lsp/284" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff-lsp/283?utm_source=stack-comment).

**Comment by zanieb** [comment]
Can we avoid this? It'd be preferable to support an older version still and just toggle this behavior depending on the Ruff version (as we do for several other features)

**Comment by dhruvmanila** [comment]
I guess it could be avoided but then the Notebook support will be available only if the user has v0.1.0.

**Comment by zanieb** [comment]
That seems preferable to me, but might be worth some more opinions. We opted for that approach in #266

**Comment by dhruvmanila** [comment]
Implementation is simple because it's just a `dict.get("cell")`.

**Pull request closed without merging**
