### PR TITLE
Show documentation in LSP output

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Looks like this, and links to the docs:

Screen Shot 2023-06-19 at 5 06 52 PM

### CODE REVIEW

**Comment by yaegassy** [comment]
Hi, @charliermarsh 

Are there any plans to add a feature in the future where the URL of the codeDescription.href in this diagnostics can be opened from a code action, similar to ESLint?

**Comment by yaegassy** [comment]
Ah, I found a comment on the ruff-vscode side. I'm looking forward to the new features being added. https://github.com/astral-sh/ruff-vscode/issues/190#issuecomment-1596292478

**Comment by charliermarsh** [comment]
Do you think that's a useful feature? I was a little torn on it.

**Comment by yaegassy** [comment]
YES, I think it's an incredibly useful feature! I experimented by adding code actions on the client side in the editor I'm using.

https://github.com/astral-sh/ruff-lsp/assets/188642/aac608fb-6143-4194-8c5a-7efb8982d25b

**Pull request merged**
